### ISSUE TITLE
version number needs to be stored in a single location

### ISSUE THREAD

**Issue by csdfgraham** [cockpit-project/starter-kit#200]
There are different version numbers stored in:

- package.json, "0.1.0"
- manifest.json "0.1" 
- cockpit-starter-kit.spec.in "1%{?dist}"

Which one is correct?

There should be a single source of truth i.e. the version number should be stored in only one location

**Comment by martinpitt** [comment]
> cockpit-starter-kit.spec.in "1%{?dist}"

This is different, it's the rpm revision (downstream change of the same upstream version), not the upstream version. This can stay as it is.

The single source of truth should be the git tag at release time. Indeed the manifest.json and package.json versions should be adjusted at `make dist-gzip` time, from the `VERSION` in Makefile.

**Comment by csdfgraham** [comment]
thanks for replying so quickly!
