### ISSUE TITLE
can stater kit be made in windows?

### ISSUE THREAD

**Issue by emaayan** [cockpit-project/starter-kit#322]
hi.. i'm wondering if i could build starter kit in my interlij IDE in windows

**Comment by martinpitt** [comment]
You should be able to build the webpack itself, even though without translations. The translation infrastructure requires a few node and shell scripts and is handled through `make`. Of course `make` itself also exists under Windows, but POSIX shell commands like  `find` or `mkdir` may not, and possibly also the gettext tools may not.

So it *should* work for basic experiments, but we don't officially support/work on that. If you are interested in working on that, we'll gladly review and adopt it of course -- like, moving more build steps out of Makefile into webpack.config.js.
