### ISSUE TITLE
Unable to 'make' with npm on Ubuntu 20.04

### ISSUE THREAD

**Issue by Rosstarz** [cockpit-project/starter-kit#475]
I have a VPS on Vultr with Ubuntu 20.04 x64
I ran sudo apt update and upgrade, then
I ran `sudo apt install nodejs` successfully
Then `sudo apt install npm` successfully aswell

All this as nonroot sudo. Then I proceeded to download `git clone https://github.com/cockpit-project/starter-kit.git`
Enter directory
Then `make`
And there's a lot of output I don't understand. But at the end it says:

------------------START--------------------
ERROR: You need to install the 'sassc' package to build this project.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! starter-kit@ build: 'webpack'
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the starter-kit@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-23T04_41_15_648Z-debug.log
make: *** [Makefile:58: dist/manifest.json] Error 1
----------------------END-------------------

And there's no /dist in the directory.
I found these `sassc` packages: https://www.npmjs.com/search?q=keywords:sassc
But am unsure I'm supposed to be installing these.
Also I've read [here](https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-20-04) that apt might not have the latest nodejs version, could that be the issue?

EDIT:
Deployed a new Ubuntu 20.04, created a sudo user, ran update and install nodejs and npm, and after make, the same error.
Here's the whole thing:

----------------------------------------------------------------------START--------------------------------------------------------
`/bin/sh: 1: rpmspec: not found
/bin/sh: 1: rpmspec: not found
/bin/sh: 1: rpmspec: not found
\# if it exists already, npm install won't update it; force that so that we always get up-to-date packages
rm -f package-lock.json
\# unset NODE_ENV, skips devDependencies otherwise
env -u NODE_ENV npm install
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

> core-js@2.6.12 postinstall /home/ubuntu/starter-kit/node_modules/attr-accept/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> core-js@3.15.2 postinstall /home/ubuntu/starter-kit/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN po2json@1.0.0-beta-3 requires a peer of commander@^6.0.0 but none is installed. You must install peer dependencies yourself.

added 750 packages from 354 contributors and audited 750 packages in 41.996s

88 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

env -u NODE_ENV npm prune
npm WARN po2json@1.0.0-beta-3 requires a peer of commander@^6.0.0 but none is installed. You must install peer dependencies yourself.

audited 750 packages in 5.654s

88 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

flock Makefile sh -ec '\
    git fetch --depth=1 https://github.com/cockpit-project/cockpit.git 242; \
    git checkout --force FETCH_HEAD -- pkg/lib; \
    git reset -- pkg/lib'
remote: Enumerating objects: 1403, done.
remote: Counting objects: 100% (1403/1403), done.
remote: Compressing objects: 100% (1251/1251), done.
remote: Total 1390 (delta 236), reused 462 (delta 50), pack-reused 0
Receiving objects: 100% (1390/1390), 6.82 MiB | 19.66 MiB/s, done.
Resolving deltas: 100% (236/236), completed with 3 local objects.
From https://github.com/cockpit-project/cockpit
 * tag               242        -> FETCH_HEAD
mv pkg/lib src/ && rmdir -p pkg
NODE_ENV= npm run build

> starter-kit@ build /home/ubuntu/starter-kit
> webpack

ERROR: You need to install the 'sassc' package to build this project.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! starter-kit@ build: \`webpack\`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the starter-kit@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-07-23T05_01_41_672Z-debug.log
make: *** [Makefile:58: dist/manifest.json] Error 1
------------------------------------------------------------END------------------------------------------------------------------

**Comment by martinpitt** [comment]
It literally means `sudo apt install sassc`. However, we have moved our other projects from sassc to dart-sass, so that this won't be necessary any more. I'll use this issue to track the migration.

**Comment by Rosstarz** [comment]
Oh, thank you Martin, you were right. Built successfully now. Thank you. 
Could be a part of the installation README if it's a dependency then.

**Comment by martinpitt** [comment]
I sent PR #476 to eliminate the sassc dependency. As I wrote, we just forgot about this in starter-kit.
