### ISSUE TITLE
index.* files

### ISSUE THREAD

**Issue by alisonken1** [cockpit-project/starter-kit#493]
Using the starter-kit, I renamed relevant src/ files to project.*

After going through find and git grep, I've also changed all the relevant entries for "starter-kit" and "index"; however, when I run make, dist/ still contains 

project.html (correct)
manifest.json (correct)
index.css (incorrect - should be project.css)
index.css.map (incorrect - should be project.css.map)
index.js (incorrect - should be project.js)
index.js.map (incorrect - should be project.js.map)

Is there something I'm missing in starter-kit that's not listed in the docs?

**Comment by martinpitt** [comment]
It's the `module.exports.entry` map in webpack.config.js. With this diff:
```diff
diff --git webpack.config.js webpack.config.js
index 5f4737b4..97045bc4 100644
--- webpack.config.js
+++ webpack.config.js
@@ -49,7 +49,7 @@ module.exports = {
         ignored: /node_modules/,
     },
     entry: {
-        index: "./src/index.js",
+        project: "./src/index.js",
     },
     // cockpit.js gets included via <script>, everything else should be bundled
     externals: { "cockpit": "cockpit" },

```

it then builds:
```
❱❱❱ ls dist
index.html  manifest.json  po.de.js  project.css  project.css.map  project.js  project.js.map
```

Honestly, the name of the webpack/.js/.css is not that important, and it's package name neutral. I wouldn't want to replicate half of the webpack documentation in starter-kit, only the cockpit specific bits.

**Comment by alisonken1** [comment]
Thanks for the info.
