### ISSUE TITLE
`Makefile` rules override existing test image

### ISSUE THREAD

**Issue by ptoscano** [cockpit-project/starter-kit#562]
With PR #542 and PR #548 I did some small improvements to the `Makefile` with the idea of using an existing image for testing. In practice, the idea is the following:
```bash
export TEST_OS=some-image
image_file=$(make print-vm)
image_name=$(basename ${image_file})
mkdir -p $(dirname ${image_file})
cp my_image.qcow2 ${image_file}.qcow2  # or symlink, or create an overlay with qemu-img, etc
ln -s ${image_name} ${image_file}
make check
```

The problem is that, because of the dependencies in the `Makefile`, the own provided image is overwritten with the image generated automatically. The dependency sequence I found was:
- `check` -> `prepare-check`
  - `prepare-check` -> `$(NODE_MODULES_TEST)` (the first dependency)
    - `$(NODE_MODULES_TEST)`: this rule unconditionally removes `package-lock.json`, which is then recreated by npm (and thus becomes newer than the file in `test/images`)
  - `prepare-check` -> `$(VM_IMAGE)` (the second dependency)
    - `$(VM_IMAGE)` -> `$(NODE_CACHE)` (the second dependency)
      - `$(NODE_CACHE)` -> `$(NODE_MODULES_TEST)`
        - since `$(NODE_MODULES_TEST)` is `package-lock.json`, which was removed and then recreated earlier, then this causes this whole dependency chain to redo the `$(VM_IMAGE)` target

A workaround here is to overwrite the qcow2 file after it was created the first time... which is what I wanted to avoid in the first place :)

The issue does not happen in case the image is not overwritten, or after the first image creation, because of the following:
https://github.com/cockpit-project/starter-kit/blob/a937b82cd2dc578c978fd88ffc1f056f47672942/Makefile#L108-L110
`$(TARFILE)` is the first dependency of `$(VM_IMAGE)`, so it means that when it is run for the first time, the timestamp of `$(NODE_MODULES_TEST)`/`package-lock.json` is changed to be the same as `package.json` (which is the dependency of `$(NODE_MODULES_TEST)`), and thus the `$(NODE_MODULES_TEST)` target is no more redone.

**Comment by martinpitt** [comment]
@ptoscano:

As the reproducer above is a bit broken (`make print-vm` prints two lines and the `echo`, we should fix that), I attempted an easier one:
```
TEST_OS=fedora-35 make vm
make check
```
The `make vm` ought to basically do your first 6 steps, but it *also* builds the source code. `make check` did not rebuild the VM, but started the tests right away. That works as intended, and I can't see anything wrong with the dependencies at first sight.

What do you actually want to do? Do you want it to use your own image as-is? Or use your own image as a basis, but build and install starter-kit from the local git checkout into it?

- If you just want to run the tests from git against your image (whatever it contains), then I'd recommend to just call `test/check-application` directly -- as then you actually don't *want* `make` to build anything.
- If for some reason you want to use `make`, you can build the tree first, and then run `touch test/image/*` to avoid rebuilding the image. 
- To further shield your own image from rebuilding, don't run it from test/images/ -- this is really the territory of the bots-built images. Run `bots/vm-run path/to/your/image.qcow2` and call the tests on it with e.g. `--machine 127.0.0.2:2201 --browser 127.0.0.2:9091`
- If you want `make vm` to build and install the local code into your custom VM, then we need to invent a way to drop the `--fresh` argument from the `vm-customize` call. (Details if/when you confirm that this is what you want).

**Comment by ptoscano** [comment]
> As the reproducer above is a bit broken (`make print-vm` prints two lines and the `echo`, we should fix that),

Oh that's easily doable, and I actually had the fix for this :-/

Proposed now as #568.

> What do you actually want to do? Do you want it to use your own image as-is? Or use your own image as a basis, but build and install starter-kit from the local git checkout into it?

Sort of: my idea is to use the cockpit CI infrastructure to run the tests of the repository on an existing image with the bits already installed. Especially that the CI infra is so nice to use... :-)

>     * If you just want to run the tests from git against your image (whatever it contains), then I'd recommend to just call `test/check-application` directly -- as then you actually don't _want_ `make` to build anything.

Thought about that; the bigger downside is that we lose the handling of naughties, which especially in the case of sub-man is critical (hello insights-client :unamused: ).

>     * If for some reason you want to use `make`, you can build the tree first, and then run `touch test/image/*` to avoid rebuilding the image.

The idea is to do something like this, but first placing the image on the expected path so the image is not built. This GH issue is the problem in this situation.

>     * To further shield your own image from rebuilding, don't run it from test/images/ -- this is really the territory of the bots-built images. Run `bots/vm-run path/to/your/image.qcow2` and call the tests on it with e.g. `--machine 127.0.0.2:2201 --browser 127.0.0.2:9091`

Thought about that too; the problem here is that we need to manage the `vm-run` lifetime ourselves (which is suboptimal).

**Comment by martinpitt** [comment]
Ah, you want this for CI. Then you can call `run-tests` directly, to get parallelism and naughties.

It generally seems difficult to change your `prepare-check` command to not update test/images/ -- that is defined as the VM image that the Makefile/bots machinery builds, so it is *intended* that make rebuilds it as soon as the code changes/gets built. We can't have test/images/ be both that place and a place to drop custom images in which never gets touched. You can work around it with `touch`, or by running `prepare-check` and *then* copying in/preparing your image. But I'd still recommend against it conceptually: Your use case wants to run tests from a clean checkout against a pre-prepared image, so calling the build system is not compatible with that idea.

**Comment by martinpitt** [comment]
@ptoscano : Do you still want to do/suggest any changes here? Right now, this doesn't seem actionable to me. Thanks!
