### ISSUE TITLE
Replace Class-Based React Components with Functional Components

### ISSUE THREAD

**Issue by Not-Sarthak** [cockpit-project/starter-kit#758]
Can we replace the Class-based Components with functional components to improve code-readability. Moreover, we can create our own component library for Cock-pit to have a proper branding kit and a set of reusable components.

**Comment by martinpitt** [comment]
In principle yes -- whenever we touch some existing code, we tend to rewrite it to functional components. Cockpit already has a set of re-usable components here: https://github.com/cockpit-project/cockpit/tree/main/pkg/lib We share these between cockpit itself, podman, machines, and other plugins. Just starter-kit itself is so simple (deliberately) to not use them, but derived projects are encouraged to do that.
